//
//  AudioEngine.swift
//  RoyalSpin
//
//  All sound playback. Effects are generated by tools/gen_audio.py and shipped as
//  mono 44.1kHz WAVs.
//
//  Built on AVAudioEngine rather than a pile of AVAudioPlayers because two things
//  here need more than fire-and-forget playback: the reel whir has to loop
//  seamlessly, and each reel's stop knock is pitched slightly differently so five
//  reels landing in sequence sound like five different pieces of metal instead of
//  the same sample five times.
//

import AVFoundation

enum Sound: String, CaseIterable {
    case leverPull  = "lever_pull"
    case reelSpin   = "reel_spin"
    case reelStop   = "reel_stop"
    case coinChing  = "coin_ching"
    case winSmall   = "win_small"
    case winNice    = "win_nice"
    case winBig     = "win_big"
    case jackpot    = "jackpot"
    case freeSpins  = "free_spins"
    case scatterHit = "scatter_hit"
    case nearMiss   = "near_miss"
    case uiTap      = "ui_tap"
    case bust       = "bust"
}

final class AudioEngine {

    static let shared = AudioEngine()

    var isMuted = false {
        didSet { if isMuted { stopLoop() } }
    }

    private let engine = AVAudioEngine()
    private var buffers: [Sound: AVAudioPCMBuffer] = [:]

    /// One-shot voices. A pool means overlapping coin sounds don't cut each other
    /// off, which matters during a jackpot cascade.
    private struct Voice {
        let player = AVAudioPlayerNode()
        let varispeed = AVAudioUnitVarispeed()
    }
    private var voices: [Voice] = []
    private var nextVoice = 0

    /// Dedicated chain for the looping whir so it can be started and stopped
    /// independently of the one-shots.
    private let loopPlayer = AVAudioPlayerNode()
    private let loopSpeed = AVAudioUnitVarispeed()
    private var loopRunning = false

    private let voiceCount = 10

    private init() {
        configureSession()
        loadBuffers()
        buildGraph()
        start()
    }

    // MARK: Setup

    private func configureSession() {
        let session = AVAudioSession.sharedInstance()
        do {
            // .ambient means the game never interrupts the player's music. A slot
            // machine is not important enough to stop someone's podcast.
            try session.setCategory(.ambient, mode: .default, options: [.mixWithOthers])
            try session.setActive(true)
        } catch {
            print("[audio] session setup failed: \(error)")
        }
    }

    private func loadBuffers() {
        for sound in Sound.allCases {
            guard let url = Bundle.main.url(forResource: sound.rawValue, withExtension: "wav") else {
                print("[audio] missing \(sound.rawValue).wav — run tools/gen_audio.py")
                continue
            }
            do {
                let file = try AVAudioFile(forReading: url)
                guard let buffer = AVAudioPCMBuffer(pcmFormat: file.processingFormat,
                                                    frameCapacity: AVAudioFrameCount(file.length))
                else { continue }
                try file.read(into: buffer)
                buffers[sound] = buffer
            } catch {
                print("[audio] failed to load \(sound.rawValue): \(error)")
            }
        }
    }

    private func buildGraph() {
        let format = buffers.values.first?.format
            ?? AVAudioFormat(standardFormatWithSampleRate: 44100, channels: 1)!

        for _ in 0 ..< voiceCount {
            let v = Voice()
            engine.attach(v.player)
            engine.attach(v.varispeed)
            engine.connect(v.player, to: v.varispeed, format: format)
            engine.connect(v.varispeed, to: engine.mainMixerNode, format: format)
            voices.append(v)
        }

        engine.attach(loopPlayer)
        engine.attach(loopSpeed)
        engine.connect(loopPlayer, to: loopSpeed, format: format)
        engine.connect(loopSpeed, to: engine.mainMixerNode, format: format)
    }

    private func start() {
        do {
            engine.prepare()
            try engine.start()
        } catch {
            print("[audio] engine failed to start: \(error)")
        }
    }

    // MARK: Playback

    /// Play a one-shot. `rate` shifts pitch and speed together (1.0 = unchanged);
    /// `volume` is linear 0...1.
    func play(_ sound: Sound, rate: Float = 1.0, volume: Float = 1.0) {
        guard !isMuted, let buffer = buffers[sound] else { return }
        restartIfNeeded()

        let voice = voices[nextVoice]
        nextVoice = (nextVoice + 1) % voices.count

        voice.varispeed.rate = rate
        voice.player.volume = volume
        // Stopping first frees the voice if it's still mid-sound from an earlier hit.
        voice.player.stop()
        voice.player.scheduleBuffer(buffer, at: nil, options: [], completionHandler: nil)
        voice.player.play()
    }

    /// The reel whir, looping until `stopLoop()`.
    func startLoop(rate: Float = 1.0) {
        guard !isMuted, !loopRunning, let buffer = buffers[.reelSpin] else { return }
        restartIfNeeded()
        loopSpeed.rate = rate
        loopPlayer.volume = 0.55
        loopPlayer.scheduleBuffer(buffer, at: nil, options: [.loops], completionHandler: nil)
        loopPlayer.play()
        loopRunning = true
    }

    func setLoopRate(_ rate: Float) {
        loopSpeed.rate = max(0.5, min(2.0, rate))
    }

    func stopLoop() {
        guard loopRunning else { return }
        loopPlayer.stop()
        loopRunning = false
    }

    /// Reel `index` landing. Each reel gets its own pitch so the staggered stop
    /// reads as five distinct mechanisms.
    func playReelStop(index: Int) {
        let rates: [Float] = [1.12, 1.06, 1.0, 0.95, 0.90]
        play(.reelStop, rate: rates[min(index, rates.count - 1)], volume: 0.85)
    }

    /// Pick the celebration that matches the size of the win.
    func playWin(tier: WinTier) {
        switch tier {
        case .none:    break
        case .small:   play(.winSmall, volume: 0.7)
        case .nice:    play(.winNice, volume: 0.8)
        case .big:     play(.winBig, volume: 0.9)
        case .mega:    play(.winBig, rate: 0.94, volume: 1.0)
        case .jackpot: play(.jackpot, volume: 1.0)
        }
    }

    /// A cascade of coins for counting up a big win — call with increasing `step`.
    func playCoin(step: Int) {
        // Walk the pitch up as the counter climbs; it makes the tally feel like it's
        // building rather than just repeating.
        let rate = 1.0 + Float(min(step, 12)) * 0.045
        play(.coinChing, rate: rate, volume: 0.42)
    }

    /// AVAudioEngine stops on interruptions (a call, another app grabbing the route).
    private func restartIfNeeded() {
        guard !engine.isRunning else { return }
        start()
    }
}
