package com.royalspin.game

import android.app.Application
import android.content.Context
import android.media.AudioAttributes
import android.media.SoundPool
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.viewModelScope
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableIntStateOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import com.royalspin.R
import com.royalspin.core.*
import kotlinx.coroutines.Job
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import java.security.SecureRandom
import kotlin.math.pow

// ────────────────────────────────────────────────────────────────────── Audio ──

/**
 * Sound playback via [SoundPool].
 *
 * SoundPool rather than MediaPlayer because every effect here is short, several
 * overlap (a coin cascade during a jackpot), and it supports per-play rate — which
 * is how each reel's stop knock gets its own pitch so five reels landing in sequence
 * sound like five different mechanisms rather than one sample five times.
 *
 * Effects are generated by tools/gen_audio.py into res/raw.
 */
class SoundEngine(context: Context) {

    private val pool: SoundPool = SoundPool.Builder()
        .setMaxStreams(12)
        .setAudioAttributes(
            AudioAttributes.Builder()
                // GAME (not MEDIA) so the app never pauses the user's music.
                .setUsage(AudioAttributes.USAGE_GAME)
                .setContentType(AudioAttributes.CONTENT_TYPE_SONIFICATION)
                .build()
        )
        .build()

    private val ids = mutableMapOf<Sfx, Int>()
    private val loaded = mutableSetOf<Int>()
    private var loopStream = 0

    var muted = false
        set(value) { field = value; if (value) stopLoop() }

    enum class Sfx(val res: Int) {
        LEVER_PULL(R.raw.lever_pull),
        REEL_SPIN(R.raw.reel_spin),
        REEL_STOP(R.raw.reel_stop),
        COIN_CHING(R.raw.coin_ching),
        WIN_SMALL(R.raw.win_small),
        WIN_NICE(R.raw.win_nice),
        WIN_BIG(R.raw.win_big),
        JACKPOT(R.raw.jackpot),
        FREE_SPINS(R.raw.free_spins),
        SCATTER_HIT(R.raw.scatter_hit),
        NEAR_MISS(R.raw.near_miss),
        UI_TAP(R.raw.ui_tap),
        BUST(R.raw.bust),
    }

    init {
        pool.setOnLoadCompleteListener { _, sampleId, status ->
            if (status == 0) loaded.add(sampleId)
        }
        for (s in Sfx.entries) ids[s] = pool.load(context, s.res, 1)
    }

    /** [rate] shifts pitch and speed together (1.0 = unchanged). */
    fun play(sfx: Sfx, rate: Float = 1f, volume: Float = 1f) {
        if (muted) return
        val id = ids[sfx] ?: return
        if (id !in loaded) return          // still decoding; skip rather than stutter
        pool.play(id, volume, volume, 1, 0, rate)
    }

    fun startLoop() {
        if (muted || loopStream != 0) return
        val id = ids[Sfx.REEL_SPIN] ?: return
        if (id !in loaded) return
        loopStream = pool.play(id, 0.5f, 0.5f, 0, -1, 1f)   // -1 = loop forever
    }

    fun stopLoop() {
        if (loopStream != 0) { pool.stop(loopStream); loopStream = 0 }
    }

    /** Each reel gets its own pitch so the staggered stop reads as five mechanisms. */
    fun reelStop(index: Int) {
        val rates = floatArrayOf(1.12f, 1.06f, 1.0f, 0.95f, 0.90f)
        play(Sfx.REEL_STOP, rates[index.coerceIn(0, rates.lastIndex)], 0.85f)
    }

    fun win(tier: WinTier) = when (tier) {
        WinTier.NONE -> Unit
        WinTier.SMALL -> play(Sfx.WIN_SMALL, volume = 0.7f)
        WinTier.NICE -> play(Sfx.WIN_NICE, volume = 0.8f)
        WinTier.BIG -> play(Sfx.WIN_BIG, volume = 0.9f)
        WinTier.MEGA -> play(Sfx.WIN_BIG, rate = 0.94f)
        WinTier.JACKPOT -> play(Sfx.JACKPOT)
    }

    /** Walk the pitch up as a win counter climbs, so the tally feels like it builds. */
    fun coin(step: Int) = play(Sfx.COIN_CHING, 1f + step.coerceAtMost(12) * 0.045f, 0.42f)

    fun release() { pool.release() }
}

// ────────────────────────────────────────────────────────────────── Game state ──

class GameViewModel(app: Application) : AndroidViewModel(app) {

    companion object {
        const val STARTING_CREDITS = 5_000
        val BET_LEVELS = listOf(1, 2, 5, 10, 25, 50, 100)
        private const val PREFS = "royalspin"
    }

    private val prefs = app.getSharedPreferences(PREFS, Context.MODE_PRIVATE)
    val sound = SoundEngine(app)

    private val machine: SlotMachine

    var credits by mutableIntStateOf(0); private set
    var displayCredits by mutableIntStateOf(0); private set
    var betPerLine by mutableIntStateOf(1); private set
    var freeSpinsRemaining by mutableIntStateOf(0); private set
    var isSpinning by mutableStateOf(false); private set
    var lastResult by mutableStateOf<SpinResult?>(null); private set
    var message by mutableStateOf<String?>(null); private set
    var nearMissBanner by mutableStateOf<NearMiss?>(null); private set

    var volatility by mutableStateOf(Volatility.BRUTAL)
        private set
    var muted by mutableStateOf(false)
        private set

    private var countUpJob: Job? = null
    private var bannerJob: Job? = null

    val totalBet: Int get() = betPerLine * Paylines.count
    val isFreeSpin: Boolean get() = freeSpinsRemaining > 0
    val canSpin: Boolean get() = !isSpinning && (freeSpinsRemaining > 0 || credits >= totalBet)

    init {
        // A seed is minted once per install and kept. Combined with the persisted
        // spin count, a returning player continues their own unique stream rather
        // than replaying the same sequence from launch — which is what "every player
        // gets a different set" actually requires.
        var seed = prefs.getLong("seed", 0L)
        if (seed == 0L) {
            seed = SecureRandom().nextLong().let { if (it == 0L) 1L else it }
            prefs.edit().putLong("seed", seed).apply()
        }

        volatility = runCatching {
            Volatility.valueOf(prefs.getString("volatility", null) ?: "BRUTAL")
        }.getOrDefault(Volatility.BRUTAL)
        muted = prefs.getBoolean("muted", false)
        sound.muted = muted

        machine = SlotMachine(
            seed = seed,
            volatility = volatility,
            nearMiss = NearMissConfig.DEFAULT,
        )
        machine.advanceTo(prefs.getLong("spinCount", 0L))

        credits = prefs.getInt("credits", STARTING_CREDITS)
        displayCredits = credits
        betPerLine = prefs.getInt("bet", 1)
        freeSpinsRemaining = prefs.getInt("freeSpins", 0)
    }

    // ── Betting ──

    fun adjustBet(delta: Int) {
        if (isSpinning) return
        val i = BET_LEVELS.indexOf(betPerLine).takeIf { it >= 0 } ?: 0
        val next = (i + delta).coerceIn(0, BET_LEVELS.lastIndex)
        if (next == i) return
        betPerLine = BET_LEVELS[next]
        sound.play(SoundEngine.Sfx.UI_TAP, volume = 0.5f)
        save()
    }

    fun canAdjustBet(up: Boolean): Boolean {
        val i = BET_LEVELS.indexOf(betPerLine).takeIf { it >= 0 } ?: return true
        return if (up) i < BET_LEVELS.lastIndex else i > 0
    }

    fun maxBet() {
        if (isSpinning) return
        // Highest level we can actually afford, so the button never traps the player
        // in a bet they can't cover.
        betPerLine = BET_LEVELS.lastOrNull { it * Paylines.count <= credits } ?: BET_LEVELS[0]
        sound.play(SoundEngine.Sfx.UI_TAP, volume = 0.5f)
        save()
    }

    // ── Spin lifecycle ──

    /**
     * Produces the result and deducts the stake. The renderer then animates toward it
     * and calls [spinDidFinish] once the last reel lands.
     */
    fun beginSpin(): SpinResult? {
        if (!canSpin) {
            if (credits < totalBet && freeSpinsRemaining == 0) {
                message = "Out of credits — reset to keep playing."
                sound.play(SoundEngine.Sfx.BUST, volume = 0.7f)
            }
            return null
        }

        countUpJob?.cancel()
        displayCredits = credits
        nearMissBanner = null
        message = null
        isSpinning = true

        if (freeSpinsRemaining > 0) freeSpinsRemaining-- else {
            credits -= totalBet
            displayCredits = credits
        }

        val result = machine.spin(betPerLine)
        lastResult = result

        sound.play(SoundEngine.Sfx.LEVER_PULL)
        sound.startLoop()
        save()
        return result
    }

    fun reelDidStop(index: Int) {
        sound.reelStop(index)
        // Chime if this reel banked a scatter, so progress toward the bonus is
        // audible reel by reel rather than only at the end.
        val grid = lastResult?.grid ?: return
        if (index in grid.indices && grid[index].any { it.isScatter }) {
            sound.play(SoundEngine.Sfx.SCATTER_HIT, volume = 0.6f)
        }
    }

    fun spinDidFinish() {
        val result = lastResult
        sound.stopLoop()
        isSpinning = false
        if (result == null) return

        if (result.totalWin > 0) {
            credits += result.totalWin
            sound.win(result.tier)
            countUp(credits, result.tier)
        } else {
            displayCredits = credits
        }

        if (result.freeSpinsAwarded > 0) {
            freeSpinsRemaining += result.freeSpinsAwarded
            message = "${result.freeSpinsAwarded} FREE SPINS!"
            sound.play(SoundEngine.Sfx.FREE_SPINS)
        } else if (result.totalWin == 0) {
            result.nearMiss?.let { showNearMiss(it) }
        }
        save()
    }

    private fun showNearMiss(nm: NearMiss) {
        nearMissBanner = nm
        sound.play(SoundEngine.Sfx.NEAR_MISS, volume = 0.75f)
        bannerJob?.cancel()
        bannerJob = viewModelScope.launch {
            delay(2_200)
            nearMissBanner = null
        }
    }

    /** Tick the counter up to the new total, with a coin sound every few steps. */
    private fun countUp(target: Int, tier: WinTier) {
        countUpJob?.cancel()
        val start = displayCredits
        if (target <= start) { displayCredits = target; return }

        // Bigger wins get a longer tally, capped so a jackpot doesn't lock the
        // player out of spinning for ten seconds.
        val durationMs = when (tier) {
            WinTier.JACKPOT -> 3000L
            WinTier.MEGA -> 2200L
            WinTier.BIG -> 1600L
            WinTier.NICE -> 1000L
            else -> 500L
        }
        val steps = (durationMs / 42).toInt().coerceIn(1, 48)

        countUpJob = viewModelScope.launch {
            for (i in 1..steps) {
                delay(durationMs / steps)
                val t = i.toDouble() / steps
                val eased = 1 - (1 - t).pow(2)          // slow as it approaches
                displayCredits = start + ((target - start) * eased).toInt()
                if (i % 3 == 0) sound.coin(i / 3)
            }
            displayCredits = target
        }
    }

    // ── Settings ──

    fun setVolatility(v: Volatility) {
        volatility = v; machine.volatility = v; save()
    }

    fun setMuted(on: Boolean) { muted = on; sound.muted = on; save() }

    fun resetCredits() {
        credits = STARTING_CREDITS
        displayCredits = credits
        freeSpinsRemaining = 0
        message = null
        sound.play(SoundEngine.Sfx.UI_TAP)
        save()
    }

    private fun save() {
        prefs.edit()
            .putInt("credits", credits)
            .putInt("bet", betPerLine)
            .putInt("freeSpins", freeSpinsRemaining)
            .putLong("spinCount", machine.spinCount)
            .putString("volatility", volatility.name)
            .putBoolean("muted", muted)
            .apply()
    }

    override fun onCleared() {
        super.onCleared()
        sound.release()
    }
}
